### ISSUE TITLE
Vairs neatskaņo kanālus (risinājums - izdzēst settings.xml failu un pa jaunu ievadīt credentials)

### ISSUE THREAD

**Issue by reinisb** [martinsbalodis/xbmc-lattelecom.tv#10]
Sveiciens,

No šodienas man addons vairs nestrādā (vakar vakarā viss strādāja). Līdz kanālu sarakstam tieku, taču tiklīdz nospiežu uz kanāla, tā izmet kļūdu, ka failed to play back file. Paskatoties log failā, var redzēt, ka ielogojoties tiek dabūts tokens, taču tas izskatās nepareizs - un attiecīgi kad kodi mēģina sākt atskaņot strīmu ar šo tokenu (aka mēģina lejupielādēt playlist.m3u8), taču nofailo, jo tiek atgriezts http 403, ka access denied. Izrietoši, ir aizdomas, ka lattelecom kaut ko ir pamainījuši tokena ieguves procesā. Par to, ka kaut kas nav kārtībā ar tokenu, liecina tas, ka ieejot shortcut.lv tokens atšķiras garuma un satura ziņā no iekš kodi iegutā.

Vai šis notiek arī jums? 

Lūk, log fails (403 errors 1055. rindā):
[kodi.log](https://github.com/martinsbalodis/xbmc-lattelecom.tv/files/1836816/kodi.log)

**Comment by martinsbalodis** [comment]
Man bija līdzīga problēma. Problēma ir tur, ka shortcut API tokens tiek glabāts uz diska un netiek atjaunots. LTC savā pusē laikam nodzēš sesiju tokenus, kas rada problēmu, ka esošais tokens ir nederīgs. 

Ātrais risinājums ir izdzēst addona konfigurācijas failu un pārkonfigurēt login datus. `.kodi` mapē bija kaut kāds xml failiņš.

**Comment by reinisb** [comment]
Ok paldies par ātro atbildi. Apstiprinu, ka ātrais risinājums (izdzēst to settings.xml failu un pa jaunu ievadīt credentials) līdzēja - addons atkal strādā.

Šo issue var te atstāt - ja nu kāds cits saskaras ar šo problēmu. Ilgtermiņā šo varētu uzlabot...varbūt pats kādreiz pieķeršos.

PS Es šobrīd testēju modifikāciju, kas strimus atskaņo nevis ar iebūvēto ffmpeg (izrietoši strīms ilgi ielādējas un vēlāk mēdz ķerties), bet gan ar jauno inputstream.adaptive - starpība ir ievērojama - strīms atveras momentāli un arī pēc tam neķeras. Padošu ziņu kā veicas...

**Comment by Janhouse** [comment]
Oh, es jau gandrīz sāku pētīt.

@martinsbalodis updeitot tokenu, ja vecais izmet kļūdu?

@reinisb labas ziņas par inputstream.adaptive! 👍 

Starpcitu, iepriekš pētot sapratu, ka par EPG nevar būt ne runas, jo tās fīčas nav pieejamas no Python API, bet vai kāds ir pētījis vai strīmam var uzsetot metadatus izmantojot Python API?

**Comment by martinsbalodis** [comment]
@Janhouse vienkāršāk nav izdzēst tokenu pēc restarta?

**Comment by Janhouse** [comment]
@martinsbalodis manam televizoram parasti ir liels uptime, negribētu restartēt tikai tāpēc, lai varētu noskatīties Panorāmu. 😆

**Comment by reinisb** [comment]
Update par inputstream.adaptive. Esmu kontaktā ar tā developeri - viņš vakar izlaboja vienu bug un tagad varu apstiprināt, ka uz jaunākā Kodi v18 nightly (kurš ietver arī inputstream.adaptive v2.2.8) lattelecom addons (ar nelielām modifikācijām) lieliski atskaņo strīmus izmantojot inputstream.adaptive (ffmpeg vietā).

Tas inputstream.adaptive developeris solījās, ka kaut kādā brīdī backportos jaunāko versiju arī uz Kodi v17, taču nav zināms, kad tas notiks. Respektīvi, kas toč ir zināms, ka tiklīdz būs oficiāli ārā kodi v18, tā būs iespēja modificēt lattelecom addonu. Kādas jūsu domas? Vai palikt pie esošā stock ffmpeg, vai mainīt uz inputstream.adaptive? Varbūt to uztaisīt kā settingu? Varbūt kāds grib notestēt? Būtībā esošajā addonā ir jāizdzēš divas rindiņas un to vietā jāpievieno septiņas jaunas.

**Comment by Janhouse** [comment]
@reinisb varbūt var detektēt supportu tai fīčai un izmantot, ja ir pieejama. Tad nebūtu problēmas ar vecām Kodi versijām.

**Comment by reinisb** [comment]
@Janhouse - makes sense. Es šo ielieku savā to-do - pieķeršos, kad strādājošs inputstream.adaptive būs pieejams kodi v17 vai arī kad tiks izlaists kodi v18.

**Comment by reinisb** [comment]
@Janhouse un @martinsbalodis - es baigi novērtētu, ja jūs varētu salabot to bug ar tokenu. Konteksts - man ir vairāki pazīstami šī addona lietotāji un visi šim bug laika gaitā uzduras - un tad izstāstīt kā izdzēst hidden (!) settings.xml failu ir baaaigi čakarīgi. Arī pats šim bugam regulāri uzduros.

**Comment by Janhouse** [comment]
Diemžēl es tuvākajā laikā nevarēšu tam pieķerties.

**Comment by Janhouse** [comment]
Beidzot ir iemerdžots @martinsbalodis repozitorijā un piedāvāts kā relīze, veru ciet.
