### ISSUE TITLE
TV sadaļas un EPG atbalsts

### ISSUE THREAD

**Issue by Janhouse** [martinsbalodis/xbmc-lattelecom.tv#11]
TV sadaļas un EPG atbalstu varētu panākt izmantojot https://github.com/kodi-pvr/pvr.iptvsimple

Ir pāris varianti:
- Forkot pvr.iptvsimple un veikt izmaiņas tajā.
- Izveidot m3u playlist un epg xml failu ko iebarot pvr.iptvsimple.

Pirmais variants problemātisks, jo tad katrai platformai jākompilē sava binārā versija, kā arī jāuztur up to date ar upstream repo, jo pie lielajām Kodi versiju maiņām plugins var nestrādāt. Kā arī jāatsakās no Python.

Otrajā variantā mīnusi, ka ar roku jāpieinstalē  iptv simple client addons un jāiekonfigurē tajā ceļš uz uzģenerētajiem m3u un xml failiem.

Varētu sākt ar to, ka pievienotu jaunu settingu esošajam addonam "Uzģenerēt IPTV Simple Client datus", un tad ar roku būtu jāveic izmaiņas pvr addona settingos.
Tā kā EPG vajag updeitot, varētu pie reizes addonu piereģistrēt kā servisu kas periodiski ievāktu jaunāko TV programmu, kā arī atjaunotu lattelecom tokenu, tādejādi atrisinot keisu nr #10 

Nākotnē varētu apskatīt iespēju piedāvāt lietotājam uzinstalēt nepieciešamo pvr addonu automātiski, kā arī iesetot konfigurāciju pvr addonā caur api, vai izmantojot kodi remote control fīču (ja tā ir ieslēgta).
#8

**Comment by reinisb** [comment]
Plāns izklausās labs! Labprāt piedalītos ar testēšanu!

**Comment by Janhouse** [comment]
Var patestēt sākotnējo versiju.
Tikai čakarīgi, ka vajag uzinstalēt pvr.iptvsimple addonu. Uz dažām platformām tas addons ir Kodi oficiālajā repo, bet uz citām (raspberry) nav. Uz Archlinux arī bija jāinstalē caur AUR.

<img width="1278" alt="Screenshot 2019-03-11 at 21 33 05" src="https://user-images.githubusercontent.com/1036439/54152392-ce889300-4445-11e9-93fb-3797cfc79e93.png">
<img width="1282" alt="Screenshot 2019-03-11 at 21 33 53" src="https://user-images.githubusercontent.com/1036439/54152396-cfb9c000-4445-11e9-91e5-197359a69504.png">

**Comment by reinisb** [comment]
Tikko notestēju uz macOS 10.14.3. Ieinstalēju tīru Kodi 18.1 un addonu no tava repo. Instalējot lattelecom addonu uzreiz piedāvāja ieinstalēt arī PVR IPTV Simple Client addonu, kā arī atvēra lattelecom addona konfigu. Konfigā ievadīju lattelecom credentials, nospiedu automātisku PVR IPTV Simple Client addona konfigu, pēc tam norestartēju Kodi un lattelecom feed caur Kodi native TV sadaļu strādā lieliski, arī EPG rādās korekti - kopumā ir baigi labi - liels paldies!

Par arhīvu - šo baigi vajadzētu, izrietoši domāju, ka mierīgi var pievienot vecajā metodē.

Edited: Par PVR IPTV Simple Client - tikko logā nočekoju, ka diemžēl tas stream atskaņošanai izmanto defaulto ffmpeg. Konteksts šeit ir tāds, ka kodi by default stream atskaņošanai izmanto iebūvēto ffmpeg, un izrietoši strīms ilgi ielādējas un vēlāk mēdz ķerties, taču ir tāds jaunums kā [inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive), kuru izmantojot stream atveras momentāli un pēc tam arī neķeras. Es pēdējo pusgadu šo lattelecom addonu lietoju ar modificētu play_channel() funkciju, kas izmanto inputstream.adaptive - strādā ideāli - varu padalīties ar kodu, ja nepieciešams.

**Comment by Janhouse** [comment]
@reinisb, jā, padalies lūdzu. Es gan sapratu, ka jaunajā kodi versijā tas playeris automātiski nomainīsies uz jauno.
Anyway, pieliekot inputstream adaptive, varētu pievienot arī pārējās video kvalitātes (ja nu Kodi mācēs noswičot dinamiski pie slikta neta).

**Comment by reinisb** [comment]
@Janhouse 
1. Komentārs par inputstream.adaptive kopumā - dīvaini ir tas, ka vismaz man uz macos clean instalējot Kodi 18.1 inputstream.adaptive addons netika ieinstēts out of the box. Tas īpaši dīvaini šķiet, jo readme pirmajā bulletā ir minēts, ka "this addon is part of the official kodi repository and **part of each kodi installation**". Vai esmu kaut ko pārpratis? Izrietoši man tas inputstream.adaptive addons bija jāieinstalē manuāli caur oficiālo kodi repository. Bet nu tā kā šis addons ir oficiālajā kodi repository, tad to tāpat kā PVR IPTV Simple Client varētu ieinstalēt reizē ar Lattelecom addona instalāciju.
2. Lai kanaalu atskanoshanaa ffmpeg vietaa izmantotu inputstream.adaptive, channels.py veicu sekojošas izmaiņas:

```
# Iekš def make_channel_list() for c in channels pievienoju sekojoshu rindu:
listitem.setProperty('IsPlayable', 'true')

# Iekš def play_channel() pashaa sakumaa pievienoju sekojosho rindu:
_handle = int(sys.argv[1])

# Iekš def play_channel() try: izdzesu sekojoshas rindas:
listitem = xbmcgui.ListItem(label="video")
xbmc.Player().play(rtmp_url, listitem)

# Iekš def play_channel() try: pievienoju sekojoshas rindas:
playitem = xbmcgui.ListItem(path=rtmp_url)
playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
playitem.setContentLookup(False)
xbmcplugin.setResolvedUrl(_handle, True, playitem)
```

**Comment by reinisb** [comment]
@Janhouse Starpcitu, tikko veicu savā iepriekšējā komentārā minēto instrukciju tavai testa versijai ar PVR IPTV Simple Client un varu apstiprināt, ka tagad kanāli caur native TV tiek atskaņoti ar inputstream.adaptive! Tad sanāk, ka PVR IPTV Simple Client izmanto lattelecom addonu, un izrietoši manu channels.py inputstream.adaptive modifikāciju, lai atskaņotu kanālu?

**Comment by Janhouse** [comment]
@reinisb, iptvsimple m3u kanālu pleilistē izmantoju linku uz lattelecomtv addonu, nevis video linku (`plugin://lattelecomtv/?play=true&data_url=101`). Kodi diezgan labi supportē iekšējos linkus.
To izmantoju, jo addons pārbauda un tiek galā ar auth tokenu, kā arī netiek lieki dublēts kods.

**Comment by reinisb** [comment]
@Janhouse šis totally makes sense now - riktīgi labs! Kā noproti, es ļoti atbalstītu to, ja lattelecom addons out of the box (t.sk. arī caur native TV) kanālu atskaņošanai izmantotu nevis ffmpeg, bet inputstream.adaptive - tiesa, neesmu domājis par iespējamām blaknēm/savietojamības problēmām.

**Comment by Janhouse** [comment]
@reinisb jaunajā Kodi man Tavas koda izmaiņas strādā arī ar diseiblotu inputstream adaptive addonu.

**Comment by Janhouse** [comment]
@reinisb bet bez tā plugina neatver tik ātri. Anyway, es jau uzpušošu izmaiņas ar inputstream requirementu savā repozitorijā, pēc updeita būtu jābūt OK.
Iespējams, ka ar dikti vecāku Kodi versiju nestrādās.

**Comment by reinisb** [comment]
@Janhouse jā, ja diseiblo inputstream.adaptive addonu, tad kodi fallbacko uz defaulto ffmpeg (un tad arī izrietoši atver lēnāk).

**Comment by reinisb** [comment]
Tātad uz macos un kodi 18.1 viss strādā. Tikko izmēģināju no @Janhouse repo ieinstalēt uz mana raspberry pi (osmc, kodi 17.6) un tur pēc credentials ievadīšanas lattelecom addon konfigurācijā un tad nospiežot Open, tiek parādīt sekojošs error un kanāli netiek ielādēti ne addonā, net PVR:
**ERROR: make_channel_list (15) - 'xbmcaddon.Addon' object has no attribute 'getSettingBool'**

Vai varētu būt, ka addonā tiek izmantota kāda kodi fīča, kas vēl nebija pieejama Kodi 17.6? Kodi log izskatās šādi:
```
14:01:15.773 T:1925732864   DEBUG: CGUIMediaWindow::GetDirectory (plugin://lattelecomtv/)
14:01:15.774 T:1925732864   DEBUG:   ParentPath = [plugin://lattelecomtv/]
14:01:15.774 T:1368908544   DEBUG: Thread JobWorker start, auto delete: true
14:01:15.841 T:1627386624   DEBUG: CAddonDatabase::SetLastUsed[lattelecomtv] took 68 ms
14:01:15.842 T:1644163840   DEBUG: Thread JobWorker start, auto delete: true
14:01:15.842 T:1368908544   DEBUG: StartScript - calling plugin Lattelecom Live TV('plugin://lattelecomtv/','1','')
14:01:15.842 T:1350562560   DEBUG: Thread LanguageInvoker start, auto delete: false
14:01:15.842 T:1350562560    INFO: initializing python engine.
14:01:15.842 T:1350562560   DEBUG: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): start processing
14:01:16.099 T:1350562560   DEBUG: -->Python Interpreter Initialized<--
14:01:16.100 T:1350562560   DEBUG: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): the source file to load is "/home/osmc/.kodi/addons/lattelecomtv/addon.py"
14:01:16.100 T:1350562560   DEBUG: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): setting the Python path to /home/osmc/.kodi/addons/lattelecomtv:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
14:01:16.100 T:1350562560   DEBUG: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): entering source directory /home/osmc/.kodi/addons/lattelecomtv
14:01:16.100 T:1350562560   DEBUG: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): instantiating addon using automatically obtained id of "lattelecomtv" dependent on version 2.14.0 of the xbmc.python api
14:01:16.275 T:1925732864   DEBUG: ------ Window Init (DialogBusy.xml) ------
14:01:16.574 T:1925732864   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
14:01:16.693 T:1350562560  NOTICE: [Lattelecom Live TV v0.4.3] Initialised
14:01:16.693 T:1350562560  NOTICE: [Lattelecom Live TV v0.4.3] got URL: plugin://lattelecomtv/; 1;
14:01:16.693 T:1350562560  NOTICE: [Lattelecom Live TV v0.4.3] url-make-channelplugin://lattelecomtv/
14:01:16.785 T:1925732864   DEBUG: ------ Window Init (DialogConfirm.xml) ------
14:01:16.785 T:1925732864    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
14:01:23.710 T:1452454656   DEBUG: CWebServer[80]: request received for /jsonrpc
14:01:24.029 T:1925732864   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
14:01:24.073 T:1350562560  NOTICE: [Lattelecom Live TV v0.4.3] ERROR: make_channel_list (15) - 'xbmcaddon.Addon' object has no attribute 'getSettingBool'
14:01:24.074 T:1350562560   ERROR: Traceback (most recent call last):
14:01:24.074 T:1350562560   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/channels.py", line 15, in make_channel_list
14:01:24.076 T:1350562560   ERROR:     channels = api.get_channels()
14:01:24.076 T:1350562560   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/api.py", line 78, in get_channels
14:01:24.078 T:1350562560   ERROR:     config.login_check()
14:01:24.078 T:1350562560   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/config.py", line 91, in login_check
14:01:24.079 T:1350562560   ERROR:     if not get_setting_bool(constants.LOGGED_IN):
14:01:24.079 T:1350562560   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/config.py", line 55, in get_setting_bool
14:01:24.079 T:1350562560   ERROR:     return xbmcaddon.Addon(APPID).getSettingBool(key)
14:01:24.079 T:1350562560   ERROR: AttributeError: 'xbmcaddon.Addon' object has no attribute 'getSettingBool'
14:01:24.079 T:1350562560    INFO: CPythonInvoker(11, /home/osmc/.kodi/addons/lattelecomtv/addon.py): script successfully run
14:01:24.186 T:1452454656   DEBUG: CWebServer[80]: request received for /jsonrpc
14:01:24.230 T:1925732864   ERROR: GetDirectory - Error getting plugin://lattelecomtv/
14:01:24.232 T:1925732864   ERROR: CGUIMediaWindow::GetDirectory(plugin://lattelecomtv/) failed
14:01:24.232 T:1925732864   DEBUG: CGUIMediaWindow::GetDirectory ()
14:01:24.232 T:1925732864   DEBUG:   ParentPath = [plugin://lattelecomtv/]
```

**Comment by Janhouse** [comment]
Jā, būs jāpatestē uz vecākām versijām, negaidīju, ka nebūs iespējams pieglabāt/ielasīt boolean settingus. 😞 

Paskatījos kā Kodi ir ar arhīva supportu caur EPG, bet tur nekā laba nav. Jaunajā kodi ir iespējams marķēt EPG entrijus ar pieejamu arhīvu, bet iptvsimple tas šobrīd ir kā nepabeigts, neiemerdžots pull requests bez iespējas norādīt konkrētu linku (tā vietā izmanto time-shift). Kā arī trūkst supports tēmās, lai parādītos notifikācijas un pogas arhīva atskaņošanai.
Šķiet, ka esošā funkcionalitāte pagaidām ir "as good as it gets", jāpapusho Kodi džeki lai pieliek nepieciešamos laukus, tad uz nākamā gada relīzi varētu paspēt. 🤣 
Arhīvs jāliek atsevišķi.

Kopumā secināju - Kodi ir diezgan messy, ar ne to foršāko koda bāzi, bez dokumentācijas. Varbūt ir kādas perspektīvas alternatīvas ko izmantot uz TV?

**Comment by reinisb** [comment]
1. Par testēšanu. Dod ziņu, ja varu kā palīdzēt ar testēšanu uz vecākām Kodi versijām - man ir macOS un raspberry pi (osmc). Tajā pat laikā, vajadzētu saprast kura ir vecākā kodi versija, kura tiktu atbalstīta. Var arī darīt tā, ka teiksim atbalstām vecāko no mums pašiem nepieciešamajām versijām (17.6?) un tad ja kāds kādreiz prasa atbalstu kaut kam vēl vecākam, tad var skatīties case-by-case.
2. Par arhīvu. Ņemot vērā visu aprakstīto, domāju, ka tad ir jāliek atsevišķi, nav jau īsti variantu. Tajā pat laikā būtu vērtīgi kodi džekiem kaut kur iepostēt bulletpointus par nepieciešamajiem papildinājumiem.
3. Kopumā par alternatīvām kodi man īsti nav viedokļa.

**Comment by reinisb** [comment]
@Janhouse Šodien [OSMC izlaida update](https://osmc.tv/2019/04/osmcs-easter-update-is-here-with-kodi-v18-leia/), kas beidzot pāriet uz Kodi v18 versiju. No tava temp lattelecom addona repo ieinstalēju lattelecom tv addonu un viss strādā perfekti, turklāt ar inputstream adaptive. Patiesībā, gandrīz viss - tikko pamanīju ka EPG rāda visus raidījumus vienu stundu uz priekšu. Tas pats arī man uz macOS. Itkā Kodi settingos nepamanīju, kur varētu shiftot EPG laiku. Vai, lūdzu, vari uzmest aci vai tev ir tā pati problēma?

**Comment by Janhouse** [comment]
Jap, ievēroju problēmu ar EPG laiku. Pārgājām uz vasaras laiku un atklājās bugs. 😆 
Drīzumā safixošu.

**Comment by reinisb** [comment]
Ok, paldies!

**Comment by Janhouse** [comment]
@reinisb ir pieejams updeits. Lai redzētu izmaiņas uzreiz, pārģenerē EPG failu, izdzēs no .kodi/userdata/Database/Epg* failus un pārstartē Kodi.
Varētu iegļukot dienās kad notiek pāreja uz vasaras/ziemas laiku, bet ir cerība, ka pēc pāris gadiem tas vairs nebūs jādara. :laughing: 

@reinisb Tev inputstream adaptive stabili strādā? Man uz Archlinux mēdz ieķerties, un tad kaut kāds cache jādzēš, savādāk vairs nekas nenotiek. Es diseibloju/uninstalēju inputstream adaptive addonu un lietoju lēnajā variantā.

**Comment by reinisb** [comment]
@Janhouse paldies! github skatos, ka update versijai būtu jābūt 0.4.5, taču man iekš Kodi ne macOS, ne OSMC neizdodas redzēt pieejamo update - joprojām jaunāko versiju rāda 0.4.3. Vai varētu būt, ka kaut kas ne tā no tavā galā?

Par inputstream adaptive man viss strādā tiešām stabili - lietoju šķiet vairāk nekā pusgadu un ir tiešām smooth.

**Comment by Janhouse** [comment]
Tikko pieliku arī kategoriju, description un bildi EPG.

@reinisb aizej uz addons, left side menu -> check for updates.

**Comment by reinisb** [comment]
@Janhouse - ok, tas nostrādāja, updeitojos uz 0.4.6. Tiesa, tagad met erroru darot jebko saistībā ar Lattelecom addonu. Logā šis (izskatās, ka man nav "pytz" moduļa - man šo instalēt manuāli no šejienes? https://kodi.wiki/view/Add-on:Pytz):

```
2019-04-22 20:53:02.919 T:123145560915968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pytz
                                            Traceback (most recent call last):
                                              File "/Users/reinis/Library/Application Support/Kodi/addons/lattelecomtv/service.py", line 3, in <module>
                                                from lib import api, config, utils, exceptions, epg
                                              File "/Users/reinis/Library/Application Support/Kodi/addons/lattelecomtv/lib/epg.py", line 4, in <module>
                                                import pytz
                                            ImportError: No module named pytz
                                            -->End of Python script error report<--
2019-04-22 20:53:14.596 T:4603160000 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2019-04-22 20:53:15.761 T:123145567969280 WARNING: Previous line repeats 1 times.
2019-04-22 20:53:15.761 T:123145567969280   ERROR: GetDirectory - Error getting
2019-04-22 20:53:15.847 T:123145561452544   ERROR: Previous line repeats 6 times.
2019-04-22 20:53:15.847 T:123145561452544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pytz
                                            Traceback (most recent call last):
                                              File "/Users/reinis/Library/Application Support/Kodi/addons/lattelecomtv/addon.py", line 3, in <module>
                                                from lib import utils, channels, config, constants, epg
                                              File "/Users/reinis/Library/Application Support/Kodi/addons/lattelecomtv/lib/epg.py", line 4, in <module>
                                                import pytz
                                            ImportError: No module named pytz
                                            -->End of Python script error report<--
2019-04-22 20:53:15.873 T:123145560915968   ERROR: GetDirectory - Error getting plugin://lattelecomtv/
2019-04-22 20:53:15.874 T:4603160000   ERROR: CGUIMediaWindow::GetDirectory(plugin://lattelecomtv/) failed
2019-04-22 20:53:32.763 T:123145566818304   ERROR: GetDirectory - Error getting
2019-04-22 20:53:39.483 T:4603160000  NOTICE: stop player
```

**Comment by Janhouse** [comment]
Pamēģini vai manuāli pieliekot pytz addonu strādā. Ja strādās, tad vajag pielikt kaut kādu papildus kodu kas čeko vai tie moduļi trūkst.
Tēmām var normāli pielikt required addonus, bet citiem addoniem neesmu vēl atradis labu veidu. Uz Arch Linux nav iptvsimple, inputstream adaptive, pytz. Tie caur Archlinux paku sistēmu jāliek, tāpēc nevar pielikt hard dependency, bez kura nevar uzinstalēt.

**Comment by reinisb** [comment]
Ok, tagad viss aizgāja. Es no sākuma manuāli ieinstalēju script.module.pytz no [šejienes](https://mirrors.kodi.tv/addons/leia/script.module.pytz/). Joprojām rādīja error, attapos, ka addon.xml jāpieliek rindiņa `<import addon="script.module.pytz"/>`. Šo tad vajadzētu izdarīt jaunā versijā.

**Comment by Janhouse** [comment]
@reinisb ok, updeitoju.

**Comment by reinisb** [comment]
@Janhouse paldies! klau, viens pēdējais jautājums - ja es turpmāk turpināšu lietot tavu neoficiālo kodi repo updeitiem (kas ir baigi ērti), tad es dabūšu jaunāko versiju no šī oficiālā martinsbalodis/xbmc-lattelecom.tv ? citiem vārdiem, kā man labāk turpmāk rīkoties, lai dabūtu jaunākās versijas? Paldies vēlreiz!

**Comment by Janhouse** [comment]
Vari lietot to update repozitoriju. Nedomāju, ka tuvākajā laikā te parādīsies izmaiņas kuras es negribētu merdžot savā forkā, savukārt manas izmaiņas es iemerdžoju upstream, ja ir pārliecība, ka nepaliks sliktāk. :laughing: 

Network sadaļā var redzēt kur rodas un kur paliek visas izmaiņas. https://github.com/martinsbalodis/xbmc-lattelecom.tv/network

**Comment by reinisb** [comment]
@Janhouse  Parādījusies problēma ar EPG. Izdzēsu EPG datubāzes failu, reģenerēju EPG, bet problēma saglabājas. Proti, vertikālā līnija laika skalā laiku rāda korekti, taču pats EPG saturs ir par trīs stundām par ātru, t.i., ja patiesībā LTV1 raidījums "Krustpunktā" būs šodien 15:00-16:05, tad EPG rāda, ka tas būs 12:00-13:05. Ir idejas?
![IMG_2226](https://user-images.githubusercontent.com/6346595/57290564-5dbcca80-70c6-11e9-84f3-2d080c2607b4.JPG)

**Comment by Janhouse** [comment]
@reinisb, jā, nezinu kāpēc sāka čakarēties, bet ir risinājums.

No mana readme:

### Fixing incorrect EPG time offset

In some cases time zone settings are ignored by Kodi and EPG data is shifted incorrectly. To fix this go to IPTVSimple addon settings, set the correct time shift and then clear EPG databse by going to Kodi `Settings > PVR & Live TV > Guide > Clear data`

Vēlāk pielikšu, ka time shift automātiski uzliek IPTVSimple addona konfigurēšanas laikā.

**Comment by reinisb** [comment]
@Janhouse - forši, šis novērsa problēmu - paldies!
