### ISSUE TITLE
Nestrādā TV3, LNT, TV6 u.c. kanāli

### ISSUE THREAD

**Issue by edgars-vasiljevs** [martinsbalodis/xbmc-lattelecom.tv#16]
Sveiki

Šodien uzinstalēju addonu un viss strādā perfekti izņemot augstākminētos kanālus, kas met 403 erroru. No šī addona screenshotiem var saprast, ka LNT būtu jāiet.

Citā (Android TV) televizorā Shortcut aplikācijā visi kanāli strādā normāli ar to pašu lietotāju/paroli.

Šķiet, ka tas varētu būt saistīts ar šo:
![Selection_152](https://user-images.githubusercontent.com/456317/58101784-e10f0d80-7be8-11e9-86ab-5960368a2eda.png)

Ir idejas?

Paldies

**Comment by reinisb** [comment]
Šiem * kanāliem vajag Lattelecom IP adresi, citādāk neatrādās.

**Comment by Janhouse** [comment]
@reinisb man ir aizdomas, ka TV appos nevajag Lattelecom IP adresi (citi API izsaukumi?). Varbūt kāds var notestēt uz Samsung/LG/Android TV aplikācijām ārpus Lattelecom tīkla?

**Comment by edgars-vasiljevs** [comment]
> @reinisb man ir aizdomas, ka TV appos nevajag Lattelecom IP adresi (citi API izsaukumi?). Varbūt kāds var notestēt uz Samsung/LG/Android TV aplikācijām ārpus Lattelecom tīkla?

Man otrs TV ir ar LMT 4G internetu un viss strādā. 

Dekompilēju Shortcut Android TV aplikāciju un redzu, ka API nedaudz atšķiras - https://pastebin.com/raw/T61rW5rD

**Comment by edgars-vasiljevs** [comment]
Izskatās, ka pietiek nomainīt "get_stream_url" API linku uz v1.7 un user agent uz:
`Shortcut.lv for Android TV v1.11.9 / Dalvik/2.1.0 (Linux; U; Android 7.1.1; sdk_google_atv_x86 Build/NYC)`

Tad strādā visi kanāli.

**Comment by Janhouse** [comment]
@edgars-vasiljevs, paldies! Pārējos API izsaukumus pagaidām atstāju uz API v1.4, cerams, ka tas neradīs problēmas.
Updeits jau ir repozitorijā.

Kā ir ar tām TV un mobilajām aplikācijām? Vai strīma valodu var mainīt? Ja var, maybe caur inputstream adaptive varētu arī tās iebarot.
