### ISSUE TITLE
Pēc OSMC Kodi update uz 18.8 addons vairs nestrādā (urllib2 urlopen)

### ISSUE THREAD

**Issue by reinisb** [martinsbalodis/xbmc-lattelecom.tv#24]
Sveiki,

Upgreidoju savu raspberry pi OSMC uz jaunāko versiju, kas cita starpā Kodi updeitoja uz 18.8. Pēc update xbmc-lattelecom addon vairs nestrādā. Detaļas par manu setup: Running on Open Source Media Center 2020.10-1, kernel: Linux ARM 32-bit version 4.19.122-2-osmc, raspberry pi.

Nestrādāšana izpaužas tā, ka uzreiz pēc kodi restarta xbmc-lattelecom addons vienkārši nobrūk un saka, ka jāskatās logā. Tas pats notiek ja mēģinu atvērt kanālu sarakstu iekš addona vai mēģinu sākt atskaņot kādu no kanāliem iekš EPG. Logā errors ir `<urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:727)>` (1211 rinda pievienotajā log failā).

Izrietoši izskatās, ka problēma ar pitona urllib2 moduļa urlopen funkciju, kas tiek izmantota lai uzģenerētu kanālu sarakstu. Vai, lūdzu, variet uzmest aci? Es pieļauju, ka risinājums ir triviāls.

Paldies!

[kodi.log](https://github.com/martinsbalodis/xbmc-lattelecom.tv/files/5476784/kodi.log)

**Comment by reinisb** [comment]
Izsecinaju, ka kaut kas noiet greizi [šajā rindā](https://github.com/martinsbalodis/xbmc-lattelecom.tv/blob/83f764632d36ca2f82329625a27880db7200de37/lib/api.py#L45) - programma netiek tālāk par šo rindu. Šķiet, ka request URL un query parami ir pareizi, bet kaut kas noiet greizi tieši requesta brīdī (SSL DH_KEY_TOO_SMALL)

**Comment by Janhouse** [comment]
Man ar Kodi 18.9 strādā bez problēmām. Ar 18.8 arī strādāja.

**Comment by Janhouse** [comment]
Izskatās, ka Kodi versijai vai OSMC kaut kas nav labi ar SSL libu: https://stackoverflow.com/a/55933585

**Comment by reinisb** [comment]
Es tikko uz macOS ieinstalēju clean Kodi 18.9 ar lattelecom addonu un viss strādā perfekti. Tātad, kā jau tu raksti, kaut kas nav ok ar ar OSMC un/vai Kodi versijas compatibility. Papētīšu sīkāk.

**Comment by reinisb** [comment]
Ok, problēmu atrisināju `/etc/ssl/openssl.cnf` failā nomainot `CipherString = DEFAULT@SECLEVEL=2` uz `CipherString = DEFAULT@SECLEVEL=1` Bet būtībā problēma ir lattelecom galā.

Atsauces:
https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788

Lattelecom servera tests:
![ltc](https://user-images.githubusercontent.com/6346595/98037776-c48a8380-1e24-11eb-863d-f6aef11b936e.png)
