### ISSUE TITLE
Shortcut error

### ISSUE THREAD

**Issue by viensjenots** [martinsbalodis/xbmc-lattelecom.tv#25]
When opening channel gives error "can only concentrate str (not "int") to str"

screenshot: https://ibb.co/p0Z5x8r

**Comment by Janhouse** [comment]
Which version of Kodi is this?
I use it with latest version, but now you also need the Tet+ subscription for this to work, old Shortcut plans were cancelled by Tet.

**Comment by viensjenots** [comment]
I'm on latest kodi version. Could it be subscription error, if Helio iTV is working with my account?

**Comment by Janhouse** [comment]
Helio iTV is a different subscription.
You should test with Tet+ instead https://tet.plus/

I looked at possibility to make Helio work with Kodi but it uses some 3rd party DRM libraries and even if we integrated them into Kodi addon, we probably would not be allowed to distribute those binary files.

**Comment by viensjenots** [comment]
I don't want to add another subscription for now. Have to stick with Helio, even if the android apk very annoying to navigate with smarttv remote.
