### ISSUE TITLE
Attēla kvalitātes izvēle

### ISSUE THREAD

**Issue by wwwslaists** [martinsbalodis/xbmc-lattelecom.tv#5]
Būtu labi ja varētu izvēlēties kādā kvalitātē skatīties. Aplikācija ir pieejamas HD strems.

**Comment by reinisb** [comment]
Piekrītu @wwwslaists  - ir vairāki kanāli, kuriem ir pieejama HD kvalitāte (ne tikai aplikācijā, bet arī web vidē - pieļauju, ka stream URLs ir tie paši). Apskatot stream URL izskatās, ka vienkārši mainās vērtība no lq/hq uz hd.

@martinsbalodis - es būtu gatavs arī veikt kaut kādu donation. Kā tev izskatās ar laikiem?

**Comment by Janhouse** [comment]
Oi, es nezināju, ka ir kanāli ar "HD" izvēli. 😆

**Comment by reinisb** [comment]
@Janhouse - Piemēram, kanālam ar id 1021 ir pieejamas lq, mq, hq un hd. Ieskatījos kodā ([api.py](https://github.com/martinsbalodis/xbmc-lattelecom.tv/blob/master/resources/lib/api.py) 132 rinda un uz leju) - cik saprotu, tad šobrīd tiek ņemts stream url no pēdējā atgrieztā stream iekš data (ja id nav _lq.stream). Taču iespējamās kvalitātes ir _lq.stream, _mq.stream, _hq.stream un _hd.stream. Es teiktu, ka kā quick fix vajadzētu uztaisīt loģiku, ka vienmēr tiek ņemta augstākā kvalitāte (effectively jāņem HD, un ja nav HD tad HQ). Vai tu šo varēsi izlabot?

**Comment by reinisb** [comment]
@Janhouse - paldies - tikko izmēģināju - strādā ideāli!

**Comment by Janhouse** [comment]
Pieliku ZIP pie relīzēm
