### ISSUE TITLE
Jauns updeits.

### ISSUE THREAD

**Issue by dabuum666** [martinsbalodis/xbmc-lattelecom.tv#8]
Sveiki. Vēlētos uzzināt vai būs kāds jauns updeits ar jūsu to do listes īstenošanu?

**Comment by Janhouse** [comment]
Cik skatījos, Kodi neļauj implementēt EPG caur python API, un nedomāju, ka uzradīsies kāds, kuram būtu vēlme to uzrakstīt C. Var jau būt, ka ir kaut kādas bibliotēkas kas to ļauj implementēt vienkāršāk, bet neesmu pētījis.
Neesmu arī skatījies par kanāla informācijas provaidošanu, jo tas, manuprāt, ir diezgan mazsvarīgi.

Bet, Tu vari uztaisīt kādu no tām fīčām, un uztaisīt pull request.
